name: "🐛 Documentation Issue"
description: Create a report for an issue or a wrong part in the documentation

body:
  - type: markdown
    attributes:
      value: |
        Describe your use-case which is not covered by existing documentation. If it is easier to submit a documentation patch instead of writing an issue, just do it!

  - type: textarea
    attributes:
      label: Describe the issue in the documentation
      description: A clear and concise description what is wrong in the documentation.
    validations:
      required: true
