= Installation
:toc: left
:toclevels: 3
:icons: font

:source-highlighter: coderay
:source-language: YAML

===== xref:../README.adoc[🏠 Return to the index]

== Initial Setup

* https://www.spigotmc.org/resources/13932/[Download the plugin]
* Put "FastAsyncWorldEdit.jar" into your `plugins` folder
* Reboot the server and FAWE will generate all necessary files.

[WARNING]
Make sure your server has been launched with https://adoptium.net/[Java 17].

[WARNING]
Do not install WorldEdit! FAWE is a direct replacement.

== Third Party Plugin Support

=== Region Restrictions Systems

The following region restriction plugins are supported natively by us. Other third party plugins may not be listed:

* https://www.spigotmc.org/resources/factionsuuid.1035/[FactionsUUID]
* https://www.spigotmc.org/resources/68900/[GriefDefender]
* https://www.spigotmc.org/resources/griefprevention.1884/[GriefPrevention]
* https://www.spigotmc.org/resources/plotsquared-v6.77506/[PlotSquared v6]
* https://www.spigotmc.org/resources/towny-advanced.72694/[Towny]
* https://dev.bukkit.org/projects/worldguard[WorldGuard]

[TIP]
This can be disabled in the config or bypassed with the `/wea` command or the `fawe.bypass` permission.

=== Other Plugins

We also offer an asynchronous version of VoxelSniper that follows the restriction of FAWE:
https://dev.bukkit.org/projects/favs[FastAsyncVoxelSniper]

== Logging and Rollback

Enable `use-disk` and `use-database` in the `config.yml` to use the in built FAWE logging / rollback.

[TIP]
It is safe to give normal players access to FAWE rollback. To bypass logging use `//fast`.
